# Generated by Django 3.1.5 on 2024-03-15 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='未知', max_length=10, verbose_name='学号')),
                ('stu_name', models.CharField(default='未知', max_length=50, verbose_name='学生姓名')),
                ('score', models.FloatField(default='未录入', verbose_name='分数')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='老师姓名')),
            ],
        ),
    ]
